FROM golang:1.17

RUN apt-get update && apt-get install -y --no-install-recommends \
        gettext-base \
        curl \
    && rm -rf /var/lib/apt/lists/*

ENV JQ_VERSION=1.6

RUN wget -O /usr/local/bin/jq "https://github.com/stedolan/jq/releases/download/jq-${JQ_VERSION}/jq-linux64" \
    && chmod 755 /usr/local/bin/jq

RUN download_url=$(curl -s https://api.github.com/repos/go-swagger/go-swagger/releases/latest | \
    jq -r '.assets[] | select(.name | contains("'"$(uname | tr '[:upper:]' '[:lower:]')"'_amd64")) | .browser_download_url') \
    && curl -o /usr/local/bin/swagger -L'#' "$download_url" \
    && chmod +x /usr/local/bin/swagger

RUN go get golang.org/x/tools/cmd/goimports \
    && wget -O- -q https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/bin     && rm -rf /go/src/*




ENV CGO_ENABLED 0
