export PROJECT = user_operations
IMPORT_PATH = github.com/shahzaibaziz/${PROJECT}

MONGO_DB_CNT_ID ?=

# all non-windows environments
ROOT := $(shell pwd)

DEV_IMAGE := ${PROJECT}_dev

DOCKERRUN := docker run --rm \
	-v ${ROOT}:/usr/src/${PROJECT} \
	-w /usr/src/${PROJECT} \
	${DEV_IMAGE}
