name: Generate and Commit JSON SBOM

on:
  push:
    branches:
      - main

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Generate JSON SBOM
        uses: CycloneDX/cyclonedx-gomod@main
        with:
          path: ./CycloneDX.sln
          json: true
          github-bearer-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload SBOM as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: JSON-SBOM
          path: ./*.json

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
      - name: Commit SBOM to Repository
        run: |
          git add -f ./*.json
          git commit -m "Update SBOM" -a || echo "No changes to commit"
          git push origin HEAD:main
